"use client";

import { Wand2 } from 'lucide-react';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';

interface AIAssistantProps {
  summary: string;
}

export function AIAssistant({ summary }: AIAssistantProps) {
  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button variant="outline" size="sm">
          <Wand2 className="mr-2 h-4 w-4" />
          Get AI Summary
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-[425px]">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Wand2 className="h-5 w-5 text-primary"/>
            AI-Powered Summary
            </DialogTitle>
          <DialogDescription>
            A succinct overview of the article, generated by AI.
          </DialogDescription>
        </DialogHeader>
        <div className="py-4 text-sm text-foreground/80">
          <p>{summary}</p>
        </div>
      </DialogContent>
    </Dialog>
  );
}
